# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        xai: 10
        explainable ai: 10
        explain: 2
        gan: 10
        generative adversarial network: 5
        kaggle: 3
        deep learning: 2

# 通知の閾値
score_threshold: 0
